Projet ASPnet/Isen.DotNet.Web/Controllers/CommuneController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class CommuneController : BaseController<Commune>
    {
        public CommuneController(
            ILogger<CommuneController> logger,
            ICommuneRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Projet ASPnet/Isen.DotNet.Web/Views/Commune/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@using Isen.DotNet.Library.Repositories.Interfaces;
@{
    ViewData["Title"] = "Commune (détail)";
}
@inject IDepartementRepository _departRepository;
@model Commune


<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/commune/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Name" class="control-label">Nom de la commune :</label>
                <input type="text" class="form-control"
                    id="Name" placeholder="Nom de la commune"
                    value="@Model?.Name" asp-for="Name" />
            </div>
            <div>
                <label for="Longitude" class="control-label">Longitude :</label>
                <input type="text" class="form-control"
                    id="Longitude" placeholder="Longitude"
                    value="@Model?.Longitude" asp-for="Longitude" />
            </div>
            <div>
                <label for="Latitude" class="control-label">Latitude :</label>
                <input type="text" class="form-control"
                    id="Latitude" placeholder="Latitude"
                    value="@Model?.Latitude" asp-for="Latitude" />
            </div>
            <div>
                <label for="DepartId">
                     Departement : 
                </label>
                @Html.DropDownListFor(
                    d => d.DepartementId, new SelectList( _departRepository.GetAll(), "Id", "Name"),
                    "<Sélectionnez un département>", new { @class = "form-control" }
                    )
            </div>

            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Commune" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Projet ASPnet/Isen.DotNet.Web/Views/Commune/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Commune";
}
@model IEnumerable<Commune>

<div class="row">
    <div class="col-md-12">
        <h1>Commune <small>/commune/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Commune" asp-action="Detail">Ajouter une commune...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <!--<th>#</th>-->
                <th>Nom</th>
                <th>Longitude</th>
                <th>Latitude</th>
                <th>Departement</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var commune in Model)
            {
            <tr>
                <!--<td>@commune.Id</td>-->
                <td>@commune.Name</td>
                <td>@commune.Longitude</td>
                <td>@commune.Latitude</td>
                <td>@commune.Departement?.Name</td>
                <td>
                    <a class="btn btn-default" 
                        asp-controller="Commune" 
                        asp-action="Detail" 
                        asp-route-id="@commune.Id">Editer</a>
                    &nbsp;
            </tr>
            }
        </tbody>
    </table>
</div>