Projet ASPnet/Isen.DotNet.Web/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class PersonController : BaseController<Person>
    {
        public PersonController(
            ILogger<PersonController> logger,
            IPersonRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Projet ASPnet/Isen.DotNet.Web/Views/Person/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@using Isen.DotNet.Library.Repositories.Interfaces;
@{
    ViewData["Title"] = "Personne (détail)";
}
@inject ICityRepository _cityRepository;
@model Person

<div class="row">
    <div class="col-md-12">
        <h1>Détail d'une ville <small>/person/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form" asp-action="Detail">

            <input type="hidden" 
                value="@Model?.Id" asp-for="Id" />

            <div>
                <label for="FirstName" class="control-label">
                    Prénom :
                </label>
                <input type="text" class="form-control"
                    id="FirstName" placeholder="Prénom"
                    value="@Model?.FirstName" asp-for="FirstName" />
            </div>

            <div>
                <label for="LastName" class="control-label">
                    Prénom :
                </label>
                <input type="text" class="form-control"
                    id="LastName" placeholder="Nom"
                    value="@Model?.LastName" asp-for="LastName" />
            </div>

            <div>
                <label for="BirthDate" class="control-label">
                    Date de naissance :
                </label>
                <input type="date" class="form-control"
                    id="BirthDate" 
                    value="@Model?.BirthDate?.ToString("yyyy-MM-dd")" 
                    asp-for="BirthDate" />
            </div>

            <div>
                <label for="CityId">
                    Ville : 
                </label>
                @Html.DropDownListFor(
                    // Champ du modèle (quelle ville faut-il sélectionner)
                    // Le moteur Razor sait que p est une Personne
                    // grace à @model Person
                    p => p.CityId,
                    // Remplissage de la liste
                    new SelectList(
                        // Liste des entités qui peuplent la liste
                        // voir @using et @inject en haut de fichier
                        _cityRepository.GetAll(), 
                        // Champ de clé
                        "Id", 
                        // Champ d'affichage
                        "Name"),
                    // Item par défaut
                    "<Sélectionnez une ville>",
                    // Classe CSS
                    // Le @ n'est pas celui de Razor mais celui du C#
                    // Si on veut nommer une classe ou un champ avec un 
                    // mot clé du langage, on le fait précéder d'un @
                    new { @class = "form-control" })
            </div>


            <br />

            <input type="submit" class="btn btn-primary"
                value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Person" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Projet ASPnet/Isen.DotNet.Web/Views/Person/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Personnes";
}
@model IEnumerable<Person>

<div class="row">
    <div class="col-md-12">
        <h1>Personnes <small>/person/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Person" asp-action="Detail">Ajouter une personne...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Nom complet</th>
                <th>Naissance</th>
                <th>Age</th>
                <th>Ville</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var person in Model)
            {
            <tr>
                <td>@person.Id</td>
                <td>@person.LastName</td>
                <td>@person.FirstName</td>
                <td>@person.Name</td>
                <td>@person.BirthDate?.ToString("dddd dd MMMM yyyy")</td>
                <td>@person.Age</td>
                <td>@person.City?.Name</td>
                <td>
                    <a class="btn btn-default" 
                        asp-controller="Person" 
                        asp-action="Detail" 
                        asp-route-id="@person.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" 
                        asp-controller="Person" 
                        asp-action="Delete" 
                        asp-route-id="@person.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>